# Generated by Django 4.2.5 on 2023-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LynkLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "pinterest_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "linkedin_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "x_username",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Our_Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=10000)),
                ("service_description", models.TextField()),
            ],
        ),
    ]
