# Generated by Django 4.2.5 on 2023-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lynklocal",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
