# Generated by Django 4.2.5 on 2023-09-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lynklocal_instagram_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_Form_Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=10000, null=True)),
                ("message", models.TextField()),
            ],
        ),
    ]
