# Generated by Django 4.2.5 on 2023-09-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contact_form_submission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Our_Services",
        ),
        migrations.RemoveField(
            model_name="lynklocal",
            name="about",
        ),
        migrations.RemoveField(
            model_name="lynklocal",
            name="description",
        ),
    ]
