# Generated by Django 4.2.5 on 2023-09-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contact_form_submission_registrationoption_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact_form_submission",
            old_name="registrationOption",
            new_name="form_purpose",
        ),
        migrations.RenameField(
            model_name="contact_form_submission",
            old_name="userType",
            new_name="user_type",
        ),
        migrations.AddField(
            model_name="contact_form_submission",
            name="free_quote",
            field=models.BooleanField(default=False),
        ),
    ]
